// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZlfnLdae3-He2euIRPzJwmUfHat6dWQ',
    appId: '1:672875972225:web:27ced88f5e6f3013a3af80',
    messagingSenderId: '672875972225',
    projectId: 'flutter-ecom-776db',
    authDomain: 'flutter-ecom-776db.firebaseapp.com',
    databaseURL: 'https://flutter-ecom-776db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-ecom-776db.appspot.com',
    measurementId: 'G-0HBWCWFSS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVLbPgGfBxTgQ5cBMSx1Dtl_DD0VpWVj8',
    appId: '1:672875972225:android:bd04f14d544d46b2a3af80',
    messagingSenderId: '672875972225',
    projectId: 'flutter-ecom-776db',
    databaseURL: 'https://flutter-ecom-776db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-ecom-776db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaS3yAxUSoUN9wOaV_GvpVGzFM1bT8XPY',
    appId: '1:672875972225:ios:0d821575aa1e242fa3af80',
    messagingSenderId: '672875972225',
    projectId: 'flutter-ecom-776db',
    databaseURL: 'https://flutter-ecom-776db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-ecom-776db.appspot.com',
    iosClientId: '672875972225-e30gk3d5lbu3fo4l6kor9a03km7f4f1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcobiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaS3yAxUSoUN9wOaV_GvpVGzFM1bT8XPY',
    appId: '1:672875972225:ios:0d821575aa1e242fa3af80',
    messagingSenderId: '672875972225',
    projectId: 'flutter-ecom-776db',
    databaseURL: 'https://flutter-ecom-776db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-ecom-776db.appspot.com',
    iosClientId: '672875972225-e30gk3d5lbu3fo4l6kor9a03km7f4f1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcobiApp',
  );
}
